### ISSUE TITLE
sometimes error since 0.10.6 MPC

### ISSUE THREAD

**Issue by rickroetenberg** [davidusb-geek/emhass#332]
Hi,

Using the EMHASS addon and since version 0.10.6 with MPC I receive this error:

'''
2024-07-26 16:59:56,653 - web_server - INFO - Passed runtime parameters: {'prod_price_forecast': [0.239, 0.26, 0.268, 0.286, 0.33, 0.32, 0.282, 0.271, 0.279, 0.277, 0.27, 0.268, 0.265, 0.262, 0.258, 0.253, 0.255, 0.233, 0.225, 0.201, 0.187, 0.174, 0.175, 0.192], 'load_cost_forecast': [0.239, 0.26, 0.268, 0.286, 0.33, 0.32, 0.282, 0.271, 0.279, 0.277, 0.27, 0.268, 0.265, 0.262, 0.258, 0.253, 0.255, 0.233, 0.225, 0.201, 0.187, 0.174, 0.175, 0.192], 'pv_power_forecast': [6168, 4606, 2825, 1196, 251, 15, 0, 0, 0, 0, 0, 0, 0, 2, 182, 373, 465, 1159, 2920, 4226, 5117, 5438, 5021, 4270, 2997, 1766, 995, 413, 124, 7, 0, 0], 'prediction_horizon': 24, 'def_start_timestep': [0, 0, 0], 'def_end_timestep': [0, 0, 0], 'alpha': 0.25, 'beta': 0.75, 'num_def_loads': 3, 'weight_battery_charge': 0.0, 'weight_battery_discharge': 0.03, 'def_total_hours': [0.0, 0.0, 0.0], 'treat_def_as_semi_cont': [1, 0, 0], 'set_def_constant': [0, 0, 0], 'soc_init': 0.95}
2024-07-26 16:59:56,653 - web_server - INFO -  >> Setting input data dict
2024-07-26 16:59:56,654 - web_server - INFO - Setting up needed data
2024-07-26 16:59:56,656 - web_server - INFO - Retrieve hass get data method initiated...
2024-07-26 16:59:58,402 - web_server - INFO - Retrieving weather forecast data using method = list
2024-07-26 16:59:58,402 - web_server - INFO - Retrieving data from hass for load forecast using method = naive
2024-07-26 16:59:58,403 - web_server - INFO - Retrieve hass get data method initiated...
2024-07-26 17:00:00,688 - web_server - INFO -  >> Performing naive MPC optimization...
2024-07-26 17:00:00,688 - web_server - INFO - Performing naive MPC optimization
2024-07-26 17:00:00,699 - web_server - INFO - Perform an iteration of a naive MPC controller
2024-07-26 17:00:00,700 - web_server - ERROR - Exception on /action/naive-mpc-optim [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/emhass/web_server.py", line 168, in action_call
    opt_res = naive_mpc_optim(input_data_dict, app.logger)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/emhass/command_line.py", line 446, in naive_mpc_optim
    opt_res_naive_mpc = input_data_dict["opt"].perform_naive_mpc_optim(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/emhass/optimization.py", line 853, in perform_naive_mpc_optim
    self.opt_res = self.perform_optimization(df_input_data, P_PV.values.ravel(), P_load.values.ravel(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/emhass/optimization.py", line 230, in perform_optimization
    objective = plp.lpSum(-0.001*self.timeStep*(unit_load_cost[i]*P_grid_pos[i] + \
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pulp/pulp.py", line 2233, in lpSum
    return LpAffineExpression().addInPlace(vector)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pulp/pulp.py", line 867, in addInPlace
    for e in other:
  File "/usr/local/lib/python3.11/dist-packages/emhass/optimization.py", line 230, in <genexpr>
    objective = plp.lpSum(-0.001*self.timeStep*(unit_load_cost[i]*P_grid_pos[i] + \
                                                ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
  File "/usr/local/lib/python3.11/dist-packages/pulp/pulp.py", line 209, in __rmul__
    return LpAffineExpression(self) * other
           ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
  File "/usr/local/lib/python3.11/dist-packages/pulp/pulp.py", line 930, in __mul__
    raise const.PulpError("Cannot multiply variables with NaN/inf values")
pulp.constants.PulpError: Cannot multiply variables with NaN/inf values
2024-07-26 17:00:00,746 - web_server - INFO - Passed runtime parameters: {}
2024-07-26 17:00:00,746 - web_server - INFO -  >> Setting input data dict
2024-07-26 17:00:00,746 - web_server - INFO - Setting up needed data
2024-07-26 17:00:00,748 - web_server - INFO -  >> Publishing data...
2024-07-26 17:00:00,748 - web_server - INFO - Publishing data to HASS instance
2024-07-26 17:00:00,763 - web_server - INFO - Successfully posted to sensor.p_pv_forecast = 4606.0
2024-07-26 17:00:00,773 - web_server - INFO - Successfully posted to sensor.p_load_forecast = 801.08
2024-07-26 17:00:00,785 - web_server - INFO - Successfully posted to sensor.p_pv_curtailment = 0.0
2024-07-26 17:00:00,796 - web_server - INFO - Successfully posted to sensor.p_deferrable0 = 0.0
2024-07-26 17:00:00,807 - web_server - INFO - Successfully posted to sensor.p_deferrable1 = 0.0
2024-07-26 17:00:00,817 - web_server - INFO - Successfully posted to sensor.p_deferrable2 = 0.0
2024-07-26 17:00:00,827 - web_server - INFO - Successfully posted to sensor.p_batt_forecast = 0.0
2024-07-26 17:00:00,839 - web_server - INFO - Successfully posted to sensor.soc_batt_forecast = 100.0
2024-07-26 17:00:00,852 - web_server - INFO - Successfully posted to sensor.p_grid_forecast = -3804.92
2024-07-26 17:00:00,866 - web_server - INFO - Successfully posted to sensor.total_cost_fun_value = 9.24
2024-07-26 17:00:00,876 - web_server - INFO - Successfully posted to sensor.optim_status = Optimal
2024-07-26 17:00:00,888 - web_server - INFO - Successfully posted to sensor.unit_load_cost = 0.26
2024-07-26 17:00:00,908 - web_server - INFO - Successfully posted to sensor.unit_prod_price = 0.26
'''

If I push the MPC again it will work. Any idea how to resolve this?

**Comment by rickroetenberg** [comment]
no issue anymore after a couple of days. will close the case
