### ISSUE TITLE
SSL Error SSLCertVerificationError

### ISSUE THREAD

**Issue by rickroetenberg** [davidusb-geek/emhass#65]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "src/emhass/web_server.py", line 174, in action_call
    _ = publish_data(input_data_dict, app.logger)
  File "/usr/local/lib/python3.8/site-packages/emhass-0.4.5-py3.8.egg/emhass/command_line.py", line 467, in publish_data
    input_data_dict['rh'].post_data(opt_res_latest['P_PV'], idx_closest,
  File "/usr/local/lib/python3.8/site-packages/emhass-0.4.5-py3.8.egg/emhass/retrieve_hass.py", line 305, in post_data
    response = post(url, headers=headers, data=json.dumps(data))
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='URL', port=xxxx): Max retries exceeded with url: /api/states/sensor.p_pv_forecast (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))\

docker and home assistant have similar issue

**Comment by davidusb-geek** [comment]
Please provide more information about your setup.
If using HAOS then just leave the hass_url and token parameters in the add-on configuration pane as the string  "empty"
